services:

  # Service to build and run project
  prototype:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project:/project
    working_dir: /project
    ports:
      - "1234:1234"
    command: ./tools/tcp_hash_prototype.sh
