services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project:/project
    ports:
      - "1234:1234/tcp"
volumes:
  project:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind