services:

  # Service to build and run project
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project:/project
    working_dir: /project
    ports:
      - "1234:1234"
    command:
      - bash
      - -c
      - |
        ./tools/check_code_format.sh
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${BUILD_TYPE:-Debug} -DBUILD_UNIT_TESTS=ON -DBUILD_LOAD_TESTS=ON -DCODE_COVERAGE=${CODE_COVERAGE:-OFF}
        cmake --build build --target all -- -j4
        cd build
        ctest
        ./loadtest/loadtest

volumes:

  # Project directory
  project:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind