services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project:/project
volumes:
  project:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind