services:

  # Service to build and run project
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project:/project
    working_dir: /project
    ports:
      - "1234:1234"
    environment:
      - CC=/usr/bin/clang-12
      - CXX=/usr/bin/clang++-12
    command:
      - bash
      - -c
      - >
        echo Checking code formatting...
        && ./tools/check_code_format.sh
        &&
        echo Configuring CMake project ${BUILD_TYPE:-Debug}...
        && cmake -B build -S .
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE:-Debug}
        -DBUILD_TESTS=${BUILD_TESTS:-ON}
        -DCODE_COVERAGE=${CODE_COVERAGE:-OFF}
        -DENABLE_DEBUG_LOG=ON
        &&
        echo Building project ${BUILD_TYPE:-Debug}...
        && cmake --build build --target all -- -j4

volumes:

  # Project directory
  project:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
