name: ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: your_image_name

    - name: Run build in container
      uses: docker/compose-action@1.2.1
      with:
        compose-file: docker-compose.yml
        command: cmake .
