name: ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug, Release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Compose Up
        run: docker-compose up

      - name: Code Coverage
        run: env BUILD_LOAD_TESTS=OFF CODE_COVERAGE=ON docker-compose up builder --force-recreate --build

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: project/build/src/**/*.gcno
          badge: true
          fail_below_min: true
          format: markdown
          indicators: true
          output: both
          thresholds: '20 40'
