name: ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: project
      run: docker-compose build

    - name: Configure CMake project
      run: docker-compose run builder /bin/bash -c "cmake -B build -S project -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNIT_TESTS=ON"

    - name: Build project
      run: docker-compose run builder /bin/bash -c "cmake --build build"