name: ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug, Release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Compose Up
        run: docker-compose up

      - name: Coverage Docker Compose Up
        run: env BUILD_UNIT_TESTS=ON BUILD_LOAD_TESTS=ON CODE_COVERAGE=ON docker-compose up --remove-orphans --build --force-recreate builder
      - name: Coverage gcno Files
        run: make coverage-report

# TODO Step disabled because it fails. https://github.com/makru86/tcp-hash/actions/runs/4778413208/jobs/8494819514
#      - name: Coverage Github Badge
#        uses: irongut/CodeCoverageSummary@v1.3.0
#        with:
#          filename: build/coverage.xml
#          badge: true
#          fail_below_min: true
#          format: markdown
#          indicators: true
#          output: both
#          thresholds: '20 40'
